### ISSUE TITLE
Error when trying to estimate pose with different input RGB image

### ISSUE THREAD

**Issue by samuelmorais** [megapose6d/megapose6d#10]
Hi,

Thanks for publishing this work! If you could answer this, I would apreciate.

I managed to successfully run your example on the barbecue-sauce and it rendered the output correctly.

But when I try to run the inference on new images that I put in the folder "barbecue-sauce" with the same name (image_rgb.png) and resolution (640x480), it produces the object_data.json correctly in the "output" folder, but then, when executing the "vis-output" command, this error appears:

src/megapose/visualization/bokeh_plotter.py", line 127

ValueError: shape mismatch: value array of shape (24260,3) could not be broadcast to indexing result of shape (24260,4) 

Am I missing anything?  Here is a link to the barbacue-sauce that I used to run inference, visualize detections and visualize outputs, if you want to check: [LINK TO BARBACUE-SAUCE DIRECTORY MODIFIED](https://drive.google.com/file/d/1ptxguwUSCfNT2qa5c_21LpUuX4gZQVXR/view?usp=share_link)

`python -m megapose.scripts.run_inference_on_example barbecue-sauce --vis-output
MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Traceback (most recent call last):
  File "/home/samuel/anaconda3/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/samuel/anaconda3/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/samuel/repos/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 229, in <module>
    make_output_visualization(example_dir)
  File "/home/samuel/repos/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 181, in make_output_visualization
    fig_mesh_overlay = plotter.plot_overlay(rgb, renderings.rgb)
  File "/home/samuel/repos/megapose6d/src/megapose/visualization/bokeh_plotter.py", line 127, in plot_overlay
    rgb_overlay[mask] = rgb_rendered[mask] * 0.8 + 255 * 0.2
ValueError: shape mismatch: value array of shape (24260,3) could not be broadcast to indexing result of shape (24260,4)
`

**Comment by samuelmorais** [comment]
Nevermind, I've found the problem. It was that the RGB images that I have used as input were RGBA. After changing to RGB, it worked.
