### ISSUE TITLE
Docker image misses opencv python package

### ISSUE THREAD

**Issue by xunleiw** [megapose6d/megapose6d#36]
Hello,

The docker image built by `docker pull ylabbe/megapose6d:1.0` does not have opencv python package.

`python3 -m megapose.scripts.run_inference_on_example barbecue-sauce --vis-detections
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/xunleiw/opt_pp/megapose6d/src/megapose/__init__.py", line 21, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

**Comment by prrw** [comment]
For me it does not even have python installed
EDIT: SOrry yes I could find python3. But I get same error. cv2 is missing. Also pip is not installed.
@xunleiw Did you find a solution ?

**Comment by prrw** [comment]
@xunleiw  I solved it. Use another image from Docker hub. I have added a shell script `run_container.sh` in `docker` folder of the project repository. Here is my file.

```bash
# run_container.sh
DIR=$(pwd)/../
docker run --gpus all --rm -it --name megapose -v $DIR:$DIR tsl24/megapose6d:2.0 bash -c "unset MEGAPOSE_DATA_DIR; cd $DIR && bash"
```
and run the script inside the docker folder `bash run_container.sh`
