### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by IAM-P-LP** [megapose6d/megapose6d#45]
Hi,
Thanks for the wonderful repo.I am getting an assertion error.Can you please help on that.
![image](https://github.com/megapose6d/megapose6d/assets/54659792/202901d1-8e21-450a-a360-e268574969e0)

Traceback (most recent call last):
  File "/home/miniconda3/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/miniconda3/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pose_est_megapose6d/megapose6d/megapose/scripts/run_inference_on_example.py", line 229, in <module>
    run_inference(example_dir, args.model)
  File "/home/pose_est_megapose6d/megapose6d/megapose/scripts/run_inference_on_example.py", line 145, in run_inference
    output, _ = pose_estimator.run_inference_pipeline(
  File "/home/miniconda3/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/pose_est_megapose6d/megapose6d/megapose/inference/pose_estimator.py", line 576, in run_inference_pipeline
    data_TCO_coarse, coarse_extra_data = self.forward_coarse_model(
  File "/home/miniconda3/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/pose_est_megapose6d/megapose6d/megapose/inference/pose_estimator.py", line 413, in forward_coarse_model
    out_ = coarse_model.forward_coarse(
  File "/home/pose_est_megapose6d/megapose6d/megapose/models/pose_rigid.py", line 680, in forward_coarse
    images_crop, K_crop, boxes_rend, boxes_crop = self.crop_inputs(
  File "/home/pose_est_megapose6d/megapose6d/megapose/models/pose_rigid.py", line 216, in crop_inputs
    points = meshes.sample_points(2000, deterministic=True)
  File "/home/pose_est_megapose6d/megapose6d/megapose/lib3d/rigid_mesh_database.py", line 169, in sample_points
    return sample_points(self.points, n_points, deterministic=deterministic)
  File "/home/pose_est_megapose6d/megapose6d/megapose/lib3d/mesh_ops.py", line 79, in sample_points
    assert n_points <= points.shape[1]
AssertionError

**Comment by gachiemchiep** [comment]
@IAM-P-LP  your object doesn't have enough points man. 

```bash
# reduce 2000 in the pose_regid.py file
        meshes = self.mesh_db.select(labels)
        points = meshes.sample_points(2000, deterministic=True)
```
