### ISSUE TITLE
assert LOCAL_DATA_DIR.exists()

### ISSUE THREAD

**Issue by parkjaewoo0611** [megapose6d/megapose6d#5]
Hi, Thanks for releasing your codes.

I'm trying to follow the installation & inference guide, but I need help with the following command

"python -m megapose.scripts.run_inference_on_example barbecue-sauce --vis-detections"

which returns

Traceback (most recent call last):
  File "/home/jw/anaconda3/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jw/anaconda3/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jw/F/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 22, in <module>
    from megapose.inference.utils import make_detections_from_object_data
  File "/home/jw/F/megapose6d/src/megapose/inference/utils.py", line 32, in <module>
    from megapose.config import EXP_DIR
  File "/home/jw/F/megapose6d/src/megapose/config.py", line 65, in <module>
    assert LOCAL_DATA_DIR.exists()
AssertionError

Where should I set the LOCAL_DATA_DIR ?

And also, where should I  clone the bop_toolkit_lib in this project?

Thanks in advance.

**Comment by sp9103** [comment]
Hi,

In the case of 'run_inference_on_example', LOCAL_DATA_DIR is required to set the pretrained weight path.
if you change the line 32 of the 'config.py' file as follows, it will work.

```
LOCAL_DATA_DIR = Path(os.environ.get("MEGAPOSE_DATA_DIR", Path(PROJECT_DIR) / "data"))
```

**Comment by ylabbe** [comment]
Indeed `LOCAL_DATA_DIR` is a deprecated environment variable that was still used here.
Fixed in #6

**Comment by novrain99** [comment]
Hi, @lcl-git-3d . For this assertion error, if you want to avoid it and don't touch the source code of megapose, you could try to rename the folder in which you place the examples folder to $\tt{local \underline\space data}$.
