### ISSUE TITLE
unable to run example inference script

### ISSUE THREAD

**Issue by Ruthrash** [megapose6d/megapose6d#50]
Refer error trace below. Any thoughts/suggestions appreciated _/\_
```
python -m megapose.scripts.run_inference_on_example barbecue-sauce --vis-detections
MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
Traceback (most recent call last):
  File "/opt/conda/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/git/scratchpad/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 227, in <module>
    make_detections_visualization(example_dir)
  File "/root/git/scratchpad/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 109, in make_detections_visualization
    export_png(fig_det, filename=output_fn)
  File "/opt/conda/envs/megapose/lib/python3.9/site-packages/bokeh/io/export.py", line 120, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, scale_factor=scale_factor, driver=webdriver,
  File "/opt/conda/envs/megapose/lib/python3.9/site-packages/bokeh/io/export.py", line 271, in get_screenshot_as_png
    web_driver = webdriver_control.get(scale_factor=scale_factor)
  File "/opt/conda/envs/megapose/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 174, in get
    self.current = self.create(scale_factor=scale_factor)
  File "/opt/conda/envs/megapose/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 178, in create
    driver = self._create(kind, scale_factor=scale_factor)
  File "/opt/conda/envs/megapose/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 196, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

```

**Comment by Ruthrash** [comment]
tried: 
```
conda install -c conda-forge firefox geckodriver```

still error persists

**Comment by LucasQAQ** [comment]
I solved this problem by reinstalling geckodriver

**Comment by jerinka** [comment]
Same error, even after reinstalling, pls share if there is a solution

**Comment by KomputerMaster64** [comment]
reinstalling the packages using the command `conda install -c conda-forge firefox geckodriver` did not resolve the problem. 
Someone reocmmended downgrading the bokeh package from 3.* version (e.g. 3.3.4) to version 2.4.3. Also, I installed bokeh using pypi and not conda. I haven't been able to resolve the main error message as well as the downgrading bokeh.

**Comment by nkampouroglou** [comment]
Had the same issue and it was a problem of bokeh. Try to downgrade to bokeh==2.4.3
