### ISSUE TITLE
RuntimeError: Neither firefox and geckodriver

### ISSUE THREAD

**Issue by jerinka** [megapose6d/megapose6d#51]
Any solution for this problem? I followed exact steps in readme and installed as said in error, still error remains.

conda install -c conda-forge firefox geckodriver
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

(megapose) jerina@Imegapose6d$ python -m megapose.scripts.run_inference_on_example barbecue-sauce --vis-detections
MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
Traceback (most recent call last):
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jerina/Proj/Fuji/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 222, in <module>
    make_detections_visualization(example_dir)
  File "/home/jerina/Proj/Fuji/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 104, in make_detections_visualization
    export_png(fig_det, filename=output_fn)
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/site-packages/bokeh/io/export.py", line 120, in export_png
    image = get_screenshot_as_png(obj, width=width, height=height, scale_factor=scale_factor, driver=webdriver,
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/site-packages/bokeh/io/export.py", line 271, in get_screenshot_as_png
    web_driver = webdriver_control.get(scale_factor=scale_factor)
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 174, in get
    self.current = self.create(scale_factor=scale_factor)
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 178, in create
    driver = self._create(kind, scale_factor=scale_factor)
  File "/home/jerina/miniconda3/envs/megapose/lib/python3.9/site-packages/bokeh/io/webdriver.py", line 196, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.

**Comment by Zee0549** [comment]
Hi there, it should be the problem of the version of bokeh. Try to downgrade the bokeh from 3.* to 2.4.3

**Comment by KomputerMaster64** [comment]
Thank you for the resolution. How did you narrow cause of the error down to the bokeh version?

**Comment by Zee0549** [comment]
Hi, the problem you are facing may be an environment error. If you configure the env via:
conda env create -f conda/environment_full.yaml
conda activate megapose
pip install -e .

Try to specify the bokeh version in environment_full.yaml file (bokeh == 2.4.3), and then run the command above, it should solve the problem.

From bokeh 3.* there was a major update, it will rely on something from the browser which I have not taken a deeper look at it.
the error prompted: conda install -c conda-forge firefox geckodriver is the error message form the bokeh 3.* not the original bokeh. It may not related to the use of inference pipeline.

**Comment by Ishan-Sahu-01** [comment]
If you want to work with latest version of bokeh, you might want to consider downloading chromedriver and adding it's path in environment variable. That did the trick for me
.
