### ISSUE TITLE
Cuda error while trying to run inference script

### ISSUE THREAD

**Issue by adityaatajna** [megapose6d/megapose6d#56]
Megapose is installed via conda environment setup

python -m megapose.scripts.run_inference_on_example barbecue-sauce --run-inference 

MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
INFO:__main__:Loading model megapose-1.0-RGB-multi-hypothesis.
0:00:02.487216 - Loading model megapose-1.0-RGB-multi-hypothesis.
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
No protocol specified
INFO:__main__:Running inference.
0:00:03.358012 - Running inference.
Traceback (most recent call last):
  File "/var/ai/ai_data/miniforge3/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/var/ai/ai_data/miniforge3/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 225, in <module>
    run_inference(example_dir, args.model)
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 143, in run_inference
    output, _ = pose_estimator.run_inference_pipeline(
  File "/var/ai/ai_data/miniforge3/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/inference/pose_estimator.py", line 576, in run_inference_pipeline
    data_TCO_coarse, coarse_extra_data = self.forward_coarse_model(
  File "/var/ai/ai_data/miniforge3/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/inference/pose_estimator.py", line 413, in forward_coarse_model
    out_ = coarse_model.forward_coarse(
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/models/pose_rigid.py", line 699, in forward_coarse
    out = self.forward_coarse_tensor(x, cuda_timer=cuda_timer)
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/models/pose_rigid.py", line 627, in forward_coarse_tensor
    logits = self.net_forward(x)["renderings_logits"]
  File "/var/ai/ai_data/rathore/megapose6d/src/megapose/models/pose_rigid.py", line 333, in net_forward
    outputs[k] = head(x)
  File "/var/ai/ai_data/miniforge3/envs/megapose/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/var/ai/ai_data/miniforge3/envs/megapose/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

**Comment by laomengze** [comment]
I have the same problem, pls can you tell me how you solved it ？
