### ISSUE TITLE
No module named 'notebook.extensions'

### ISSUE THREAD

**Issue by leymane86** [megapose6d/megapose6d#62]
I am receiving the following errors when running: conda env create -f conda/environment_full.yaml
I have installed notebook and jupyter_contrib_nbextensions
Installation is running on ubuntu in a virtualbox

```

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

- /home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/nb_conda_kernels/install.py:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import iter_entry_points
Enabling nb_conda_kernels...
CONDA_PREFIX: /home/root1/miniconda3/envs/megapose
Status: enabled

| Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

/ Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

/ Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/bin/jupyter-nbextensions_configurator", line 6, in <module>
    from jupyter_nbextensions_configurator.application import main
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_nbextensions_configurator/__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'

/ Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/bin/jupyter-contrib-nbextension", line 6, in <module>
    from jupyter_contrib_nbextensions.application import main
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_nbextensions/application.py", line 7, in <module>
    from jupyter_contrib_core.notebook_compat.nbextensions import ArgumentConflict
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions'

done
ERROR conda.core.link:_execute(949): An error occurred while installing package 'conda-forge::jupyter_highlight_selected_word-0.2.0-py39hf3d152e_1005'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::jupyter_highlight_selected_word-0.2.0-py39hf3d152e_1005
location of failed script: /home/root1/miniconda3/envs/megapose/bin/.jupyter_highlight_selected_word-post-link.sh
==> script messages <==
Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>
    from ._compat.nbextensions import BaseNBExtensionApp
  File "/home/root1/miniconda3/envs/megapose/lib/python3.9/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 35, in <module>
    from notebook.nbextensions import (
ModuleNotFoundError: No module named 'notebook.nbextensions
```

**Comment by dqj5182** [comment]
@leymane86 May I ask how you solved the error?
