### ISSUE TITLE
Pose estimation get stuck during inference

### ISSUE THREAD

**Issue by Brohoya** [megapose6d/megapose6d#63]
Hello,
I am trying to run inference on a custom CAD file but the pose estimation get stuck forever while running inference. I let the script "run" for more than 30min, but anyway after the first 5 sec, I can see than my GPU is not used anymore and there is no apparent error outputted. 
Here are the logs after running `python -m megapose.scripts.run_inference_on_example plate --run-inference`:
```
MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
INFO:__main__:Loading model megapose-1.0-RGB-multi-hypothesis.
0:00:00.774737 - Loading model megapose-1.0-RGB-multi-hypothesis.
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
INFO:__main__:Running inference.
0:00:01.363524 - Running inference.
```
I specify that these logs are the same I get when running inference on the barbecue-sauce:
```
python -m megapose.scripts.run_inference_on_example barbecue-sauce --run-inference 
MKL_NUM_THREADS: 1
OMP_NUM_THREADS: 1
CUDA_VISIBLE_DEVICES: 0
EGL_VISIBLE_DEVICES: 0
INFO:__main__:Loading model megapose-1.0-RGB-multi-hypothesis.
0:00:00.818016 - Loading model megapose-1.0-RGB-multi-hypothesis.
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
Known pipe types:
  glxGraphicsPipe
(1 aux display modules not yet loaded.)
INFO:__main__:Running inference.
0:00:01.626757 - Running inference.
INFO:__main__:Wrote predictions: /home/brohoya/Documents/megapose6d/local_data/examples/barbecue-sauce/outputs/object_data.json
0:00:04.320407 - Wrote predictions: /home/brohoya/Documents/megapose6d/local_data/examples/barbecue-sauce/outputs/object_data.json
```
After I Ctrl+C to quit the inference on my custom part, I can see where the script gets stuck:
```
^CTraceback (most recent call last):
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/brohoya/Documents/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 225, in <module>
    run_inference(example_dir, args.model)
  File "/home/brohoya/Documents/megapose6d/src/megapose/scripts/run_inference_on_example.py", line 143, in run_inference
    output, _ = pose_estimator.run_inference_pipeline(
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/brohoya/Documents/megapose6d/src/megapose/inference/pose_estimator.py", line 576, in run_inference_pipeline
    data_TCO_coarse, coarse_extra_data = self.forward_coarse_model(
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/brohoya/Documents/megapose6d/src/megapose/inference/pose_estimator.py", line 413, in forward_coarse_model
    out_ = coarse_model.forward_coarse(
  File "/home/brohoya/Documents/megapose6d/src/megapose/models/pose_rigid.py", line 689, in forward_coarse
    renders = self.render_images_multiview(
  File "/home/brohoya/Documents/megapose6d/src/megapose/models/pose_rigid.py", line 384, in render_images_multiview
    render_data = self.renderer.render(
  File "/home/brohoya/Documents/megapose6d/src/megapose/panda3d_renderer/panda3d_batch_renderer.py", line 251, in render
    renders = self._out_queue.get()
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/brohoya/anaconda3/envs/megapose/lib/python3.9/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```
As it looks like it has something to do during a rendering with Panda3D, I specify that I run the script on Ubuntu 22.04, my GPU is an RTX2080ti with the Nvidia 535 driver (proprietary, tested) and 32Gb of RAM.

Here is the example I try to run the inference with if someone wants to test himself: [plate.zip](https://github.com/megapose6d/megapose6d/files/14889248/plate.zip)

Did somebody already have similar issue when testing custom parts ?

**Comment by dqj5182** [comment]
@Brohoya I am having same issue. Did you solve this problem?

**Comment by WanqingXia** [comment]
@Brohoya I have the same issue, how did you solve it?

**Comment by Brohoya** [comment]
Hi, this issue in my case was pretty blurry but what solved it was the replacement of my mesh file. I do not know what exactly was wrong but when I opened my old ply file, I found out that it had some corruption inside while it is supposed to be text lines with numbers (in the case of a ply file).
I exported my CAD again, I verified it was not corrupted manually and the program was not anymore getting stuck during inference.

**Comment by WanqingXia** [comment]
> Hi, this issue in my case was pretty blurry but what solved it was the replacement of my mesh file. I do not know what exactly was wrong but when I opened my old ply file, I found out that it had some corruption inside while it is supposed to be text lines with numbers (in the case of a ply file). I exported my CAD again, I verified it was not corrupted manually and the program was not anymore getting stuck during inference.

Thank you for the answer,  I have tried to modify my .obj file and the problem still exists.  I guess it is triggered for other reasons.
